# Generated by Django 3.2.2 on 2021-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=50, verbose_name='Логин покупателя')),
                ('item', models.CharField(max_length=50, verbose_name='Купленный камень')),
                ('total', models.PositiveIntegerField(verbose_name='Сумма')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество купленных камней')),
                ('date', models.DateTimeField(verbose_name='Дата и время операции')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Логин')),
                ('spent_money', models.PositiveIntegerField(default=0, verbose_name='Сумма потраченных средств')),
                ('gems', models.ManyToManyField(to='handler.Gem', verbose_name='Купленные камни')),
            ],
        ),
    ]
